-- require("tokyonight").setup({
--   -- use the night style
--   style = "moon",
--   tranparent = true,
--
--   styles = {
--     comments = { italic = true },
--     keywords = { italic = true },
--     functions = {},
--     variables = {},
--     -- Background styles. Can be "dark", "transparent" or "normal"
--     sidebars = "transparent", -- style for sidebars, see below
--     floats = "transparent", -- style for floating windows
--   },
--   hide_inactive_statusline = false, -- Enabling this option, will hide inactive statuslines and replace them with a thin border instead. Should work with the standard **StatusLine** and **LuaLine**.
--   dim_inactive = true, -- dims inactive windows
--   lualine_bold = true, -- When `true`, section headers in the lualine theme will be bold
--   --
--   sidebars = { "qf", "vista_kind", "terminal", "packer" },
--   -- Change the "hint" color to the "orange" color, and make the "error" color bright red
--   on_colors = function(colors)
--     colors.hint = colors.orange
--     colors.error = "#ff0000"
--   end,
--
--   on_highlights = function(hl, c)
--     local prompt = "#2d3149"
--     hl.TelescopeNormal = {
--       bg = c.bg_transparent,
--       fg = c.fg_transparent,
--     }
--     hl.TelescopeBorder = {
--       bg = c.bg_dark,
--       fg = c.bg_dark,
--     }
--     hl.TelescopePromptNormal = {
--       bg = prompt,
--     }
--     hl.TelescopePromptBorder = {
--       bg = prompt,
--       fg = prompt,
--     }
--     hl.TelescopePromptTitle = {
--       bg = prompt,
--       fg = prompt,
--     }
--     hl.TelescopePreviewTitle = {
--       bg = c.bg_dark,
--       fg = c.bg_dark,
--     }
--     hl.TelescopeResultsTitle = {
--       bg = c.bg_transparent,
--       fg = c.bg_transparent,
--     }
--   end,
--
-- })
--
